name: Bitbake Images (self-hosted)
permissions: read-all
on:
  push:
    branches: [ kirkstone-6.x.y ]
  workflow_dispatch:
    inputs:
      # trunk-ignore(checkov/CKV_GHA_7)
      machine:
        # trunk-ignore(yamllint/quoted-strings)
        description: 'Comma-separated list of MACHINEs to build for, e.g. "verdin-imx8mp","genericx86-64"'
        required: true
        default: '"verdin-imx8mp"'
      recipe:
        # trunk-ignore(yamllint/quoted-strings)
        description: 'Comma-separated list of recipes to build, e.g. "torizon-core-k3s-server","torizon-core-k3s-agent"'
        required: true
        default: '"torizon-core-k3s-server"'

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    strategy:
      matrix:
        branch: [kirkstone-6.x.y]
        machine: ${{ fromJSON(format('[{0}]', inputs.machine || '"verdin-imx8mp","genericx86-64"')) }}
        recipe: ${{ fromJSON(format('[{0}]', inputs.recipe || '"torizon-core-k3s-server","torizon-core-k3s-agent"')) }}
    env:
      name: build
      MACHINE: ${{ matrix.machine }}
      BRANCH: ${{ matrix.branch }}
      RECIPE: ${{ matrix.recipe }}
    container:
      image: torizon/crops:kirkstone-6.x.y
      options: --user root -v /share/source-download:/share/source-download:rw -v /share/sstate-cache:/share/sstate-cache:rw -v /share/deploy:/share/deploy:rw
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Environment prep
        run: |
          useradd -u 1001 -m torizon
          chown torizon:torizon /share/*
          chmod 777 /share/*
          
      - name: Initialize Repository
        run: su torizon -c "repo init -u file://$GITHUB_WORKSPACE -b ${BRANCH} -m default.xml"
          
      - name: Repo Sync
        run: su torizon -c "repo sync"

      - name: Build the Image
        run: |
          su torizon -c " \
            MACHINE=${MACHINE} EULA=1 source layers/meta-toradex-torizon/scripts/setup-environment build && \
            cp ../layers/meta-torizon-k3s/conf/template/bblayers.conf conf/bblayers.conf && \
            echo \"SSTATE_DIR = \\\"/share/sstate-cache\\\"\" >> conf/local.conf && \
            echo \"DL_DIR = \\\"/share/source-download\\\"\" >> conf/local.conf && \
            bitbake ${RECIPE}"
            
      - name: Deploy Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${RECIPE}
          path: deploy
          
      - name: Save Artifacts Locally
        run: mv deploy /share/deploy/$GITHUB_RUN_ID_${RECIPE}_${MACHINE}
            
      - name: Cleanup Workdir
        run: rm -rf $GITHUB_WORKSPACE

