# This is a basic workflow to help you get started with Actions

name: torizon-k3s-manifest_ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "kirkstone-6.x.y" branch
  push:
    branches: [ "kirkstone-6.x.y" ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Linux, X64]
    strategy:
      matrix:
        branch: [kirkstone-6.x.y]
        machine: [verdin-imx8mp]
        recipe: [torizon-core-k3s]
    env:
      name: build
      MACHINE: ${{ matrix.machine }}
      BRANCH: ${{ matrix.branch }}
      RECIPE: ${{ matrix.recipe }}
    container:
      image: torizon/crops:${BRANCH}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Initialize Repository
        run: repo init -u file://${$GITHUB_WORKSPACE} -b ${BRANCH} -m default.xml

      - name: Repo Sync
        run: repo sync

      - name: Setup the build environment
        run: MACHINE=${MACHINE} source setup-environment build
        
      - name: Build the image
        run: |
          cd build
          bitbake ${RECIPE}

